translation(HTML): live-examples/html-examples/embedded-content/iframe
webdoky/interactive-examples pull request #10
Opened 2022-08-02 05:16 UTC by undead404

2022-08-07 09:18 UTC, AdriandeCita commented on live-examples/html-examples/embedded-content/iframe.html
> +    title="Приклад супутнього фрейму"
```suggestion
    title="Приклад вбудованого фрейму"
```

2022-08-07 09:20 UTC, AdriandeCita requested changes
супутній - це ближче до "aside", ніж до "inline"

2022-08-07 11:07 UTC, undead404 commented on live-examples/html-examples/embedded-content/iframe.html
> +    title="Приклад супутнього фрейму"
По-моєму, це таки плутає: будь-який фрейм є вбудованим відносно батьківського контексту, а не лише iframe

2022-08-07 21:59 UTC, AdriandeCita commented on live-examples/html-examples/embedded-content/iframe.html
> +    title="Приклад супутнього фрейму"
саме так. А як в принципі можна зробити "супутній" фрейм? Хіба відносно іншого фрейму в одному документі? Коли два фрейми поряд, то їх напевне можна назвати "супутніми" один для одного? Але навіть тоді вони залишаться вбудованими

2022-08-08 09:10 UTC, undead404 commented on live-examples/html-examples/embedded-content/iframe.html
> +    title="Приклад супутнього фрейму"
Я маю на увазі, що поняття inline frame походить від поняття звичайного frame, коли вебсторінка розділялася на колонки чи ряди. Я освоював Веб у часи, коли таке ще було %-)

Супутній фрейм – такий фрейм, що може бути де завгодно, просто по ходу сторінки

2022-08-08 09:10 UTC, undead404 commented on live-examples/html-examples/embedded-content/iframe.html
> +    title="Приклад супутнього фрейму"
Ну ок, конкретно щодо фреймів краще "вбудований". Ех, а я мріяв про одноманітний переклад цього слова...

2022-08-08 19:52 UTC, merged