function-scale.html
webdoky/interactive-examples pull request #179
Opened 2024-08-05 18:27 UTC by astropsy999

2024-08-08 12:00 UTC, undead404 commented
Чудово, що подивився, на картинку й додав її. Іще треба внести в файл `meta.json`, який лежить поруч з файлом HTML. Подивися запис, що вказує на цей приклад, в оригінальному репо github.com/mdn/interactive-examples .

Крім цього, тут мав би бути файл CSS

2024-08-09 12:52 UTC, undead404 requested changes
Коментар на головній сторінці PR

2024-08-10 03:51 UTC, astropsy999 commented
> Чудово, що подивився, на картинку й додав її. Іще треба внести в файл `meta.json`, який лежить поруч з файлом HTML. Подивися запис, що вказує на цей приклад, в оригінальному репо github.com/mdn/interactive-examples .
> 
> Крім цього, тут мав би бути файл CSS

Вніс до meta.json. Сss файлу , здається, не має бути для цього прикладу

2024-08-10 05:13 UTC, undead404 requested changes

2024-08-10 05:13 UTC, undead404 commented on live-examples/css-examples/transforms/meta.json
> +      "title": "CSS Демо: scale()",
```suggestion
      "title": "Демо CSS: scale()",
```
Хай буде як в інших записів тут

2024-08-10 05:15 UTC, undead404 commented
І правда: файлу CSS тут не передбачено...

2024-08-10 06:11 UTC, undead404 approved these changes

2024-08-10 06:11 UTC, merged